// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD38gx0oDL5A79X8hE7qmu6356q4_SrGXo',
    appId: '1:486602688494:web:e821c67bf7348a4529b0ff',
    messagingSenderId: '486602688494',
    projectId: 'auvnet-flutter',
    authDomain: 'auvnet-flutter.firebaseapp.com',
    storageBucket: 'auvnet-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQP51h-qsBBWb26XG_m5p34oHCSO79D2U',
    appId: '1:486602688494:android:910bad03dce4fb9129b0ff',
    messagingSenderId: '486602688494',
    projectId: 'auvnet-flutter',
    storageBucket: 'auvnet-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOLTlGgjsxzfiNtnNcLYTYcbs2G5jA0bU',
    appId: '1:486602688494:ios:f052e8c9588b965029b0ff',
    messagingSenderId: '486602688494',
    projectId: 'auvnet-flutter',
    storageBucket: 'auvnet-flutter.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOLTlGgjsxzfiNtnNcLYTYcbs2G5jA0bU',
    appId: '1:486602688494:ios:f052e8c9588b965029b0ff',
    messagingSenderId: '486602688494',
    projectId: 'auvnet-flutter',
    storageBucket: 'auvnet-flutter.firebasestorage.app',
    iosBundleId: 'com.example.ecommerce',
  );
}
